### ISSUE TITLE
How to use inference of multiple models

### ISSUE THREAD

**Issue by polarisunny** [deepjavalibrary/djl-serving#1042]
How to use inference of multiple models, such as PaddleOCR, which has three models, namely det, cls, and rec. 
![image](https://github.com/deepjavalibrary/djl-serving/assets/16932704/29b5b51d-f217-42f7-8e87-55e9c4327fd6)

**Comment by frankfliu** [comment]
There are two ways to solve your problem, see the following demo:
1. User DJLServing workflow: https://github.com/deepjavalibrary/djl-demo/tree/master/djl-serving/workflows/multi-model
2. Use a custom Translator and load smaller model in the Translator

**Comment by faquir-sun** [comment]
Which of these two methods performs better?

**Comment by frankfliu** [comment]
@faquir-sun 
It's really depends on how heavy your smaller models are. 
For option 1, each model can scale up to X number of workers independently, I can leverage more CPU power concurrently. However, the communication between each workflow may cause more overhead.

For option 2, everything runs in the same thread, and there is not serialization/deserialization between models. But only one worker is used for small model. This may become bottleneck.

**Comment by faquir-sun** [comment]
For option 2, Is there any example for reference?

**Comment by frankfliu** [comment]
@faquir-sun 
Here is an example that involves two models: https://github.com/deepjavalibrary/djl/blob/master/examples/src/main/java/ai/djl/examples/inference/clip/ImageTextComparison.java

Above example treat two model equally, and use an utility function to run the inference. You can wrap one model into a custom translator if you want to.
