### ISSUE TITLE
What backend does djl-serving default to for rolling_batch?

### ISSUE THREAD

**Issue by yudhiesh** [deepjavalibrary/djl-serving#1075]
I am trying to understand whether I am using vLLM for my deployment here with the following settting:
```
option.rolling_batch = auto
```
I can't seem to find whether it defaults to lmi_dist or vLLM. I am also not sure what is lmi_dist? I can't seem to find any information about what it is.

**Comment by lanking520** [comment]
Currently, there are three backends

- `scheduler`: If you set engine to python and set rolling_batch to be `auto` or `scheduler`, we will use this. This is our default batch implementation focusing on HuggingFace Accelerate use cases.
- `lmi-dist`:  If you set engine to MPI and set rolling_batch to be `auto` or `lmi-dist`, we will use this. This is our default batch implementation focusing on tensor parallel use cases. It has flashAttention and PagedAttention implmentation, inspired from Text-Generation-Inference design
- `vllm`: If you set engine to Python and set rolling_batch to be `vllm`, we will use this. This is our batch implementation to run vllm from its library, you also need to have a `requirements.txt` installing `vllm==0.1.7` and `pandas` to use it.

**Comment by yudhiesh** [comment]
> Currently, there are three backends
> 
>     * `scheduler`: If you set engine to python and set rolling_batch to be `auto` or `scheduler`, we will use this. This is our default batch implementation focusing on HuggingFace Accelerate use cases.
> 
>     * `lmi-dist`:  If you set engine to MPI and set rolling_batch to be `auto` or `lmi-dist`, we will use this. This is our default batch implementation focusing on tensor parallel use cases. It has flashAttention and PagedAttention implmentation, inspired from Text-Generation-Inference design
> 
>     * `vllm`: If you set engine to Python and set rolling_batch to be `vllm`, we will use this. This is our batch implementation to run vllm from its library, you also need to have a `requirements.txt` installing `vllm==0.1.7` and `pandas` to use it.

Is there any documentation on how `lmi-dist` works? Just trying to see how it compares to vLLM.

**Comment by spring1915** [comment]
Can I use `scheduler` with the MPI or DeepSpeed engine?
