### ISSUE TITLE
How to allow parallel requests 

### ISSUE THREAD

**Issue by thoth42** [deepjavalibrary/djl-serving#1084]
Hi, 

with default settings the requests are executed one by one, each request waits for the next one, 

is dynamic batching the **only** way to allow more requests to be processed in parallel?

```python
# code/model.py

def handle(inputs: Input) -> Optional[Output]:
    time.sleep(2)
    # ...
```    

```python
# code/serving.properties

engine = Python
option.tensor_parallel_degree = 1
option.model_id = {{s3url}}
```

**Comment by frankfliu** [comment]
If you are using PyTorch/OnxxRuntime/XGBoost engine, they are running in multiple threading mode. DJLServing will automatically increase workers to allow more concurrent clients.

For LLM (tensor_parallel_degree is defined), the default worker is 1, you can use dynamic batch to increase concurrent client. 

You can use rolling batch feature: see: https://docs.djl.ai/docs/serving/serving/docs/modes.html#rolling-batch

**Comment by thoth42** [comment]
@frankfliu Thank you
