### ISSUE TITLE
Does deepspeed engine support Llama2 question-answering task?

### ISSUE THREAD

**Issue by YunTaoYoung** [deepjavalibrary/djl-serving#1106]
## Description
I tried to run by each entrypoint to compare their performance on Sagemaker. But the server failed to start with deepspeed entrypoint. This is my serving.properties
```
engine=Python
option.mpi_mode=true
option.entryPoint=djl_python.deepspeed
option.model_id=s3://xxx/sagemaker/models/original/Llama-2-7b-chat-hf
option.task=question-answering
option.dtype=fp16
option.trust_remote_code=true
option.tensor_parallel_degree=1
```
### Expected Behavior
The server should get started.

### Error Message
[INFO ] PyProcess - W-137-djl_vllm_data-stdout: ValueError: Unrecognized configuration class <class 'transformers.models.llama.configuration_llama.LlamaConfig'> for this kind of AutoModel: AutoModelForQuestionAnswering.

[INFO ] PyProcess - W-137-djl_vllm_data-stdout: Model type should be one of AlbertConfig, BartConfig, BertConfig, BigBirdConfig, BigBirdPegasusConfig, BloomConfig, CamembertConfig, CanineConfig, ConvBertConfig, Data2VecTextConfig, DebertaConfig, DebertaV2Config, DistilBertConfig, ElectraConfig, ErnieConfig, ErnieMConfig, FalconConfig, FlaubertConfig, FNetConfig, FunnelConfig, GPT2Config, GPTNeoConfig, GPTNeoXConfig, GPTJConfig, IBertConfig, LayoutLMv2Config, LayoutLMv3Config, LEDConfig, LiltConfig, LongformerConfig, LukeConfig, LxmertConfig, MarkupLMConfig, MBartConfig, MegaConfig, MegatronBertConfig, MobileBertConfig, MPNetConfig, MptConfig, MraConfig, MT5Config, MvpConfig, NezhaConfig, NystromformerConfig, OPTConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, SplinterConfig, SqueezeBertConfig, T5Config, UMT5Config, XLMConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig, YosoConfig.

**Comment by lanking520** [comment]
Try this way

```
engine=MPI
option.model_id=s3://xxx/sagemaker/models/original/Llama-2-7b-chat-hf
option.task=text-generation
option.rolling_batch=auto
option.dtype=fp16
option.trust_remote_code=true
option.tensor_parallel_degree=1
```

```
curl -X POST http://127.0.0.1:8080/invocations \
  -H "Content-type: application/json" \
  -d '{"inputs":"Deep Learning is","parameters":{"max_new_tokens":512, "do_sample":true}}'
```

**Comment by frankfliu** [comment]
deepspeed handler is deprecated.
