### ISSUE TITLE
Handling requests concurrently: AWS Sagemaker endpoint

### ISSUE THREAD

**Issue by sneha5gsm** [deepjavalibrary/djl-serving#1116]
Hi!
I was trying to use the AWS Deep Learning container(specifically: djl-inference:0.23.0-deepspeed0.9.5-cu118) which supports djl serving, to serve the Llama 2 13B chat model (meta-llama/Llama-2-13b-chat-hf) on an AWS sagemaker endpoint hosted on an ml.g5.12xlarge. Since this instance has 4 GPUs each of 24 GB memory, I wanted to load two copies of the model so that the endpoint would be able to serve to requests parallelly. Here’s the djl config I used: 
```
engine=DeepSpeed
option.entryPoint=djl_python.deepspeed
option.task=text-generation
option.s3url={{s3url}} 
option.tensor_parallel_degree=2 
option.parallel_loading=true 
option.dtype=fp16 
option.enable_venv=true
```

I am able to load two copies of the model on the instance and deploy it successfully, but unfortunately, I don’t see any increase in throughput. Could you help me understand why this could be the case. Am I missing something in the config?

Thanks!

**Comment by lanking520** [comment]
You should see double the throughput, but this also depends on the batch size you set. In the meantime, you can also try with our rolling batch to see if there is any performance gain

```
engine=MPI
option.task=text-generation
option.s3url={{s3url}} 
option.tensor_parallel_degree=2 
option.rolling_batch=auto
option.max_rolling_batch_size=8
option.dtype=fp16 
option.enable_venv=true
```

**Comment by sneha5gsm** [comment]
Hi @lanking520 
Thank you for the prompt response.

Yes, even I had expected the throughput to double, but my load tests didn't indicate any improvement. I was wondering if I need to enable a flag or a parameter or env variable? In fact initially I wasn't able to deploy 2 model copies on a single endpoint without enabling `option.parallel_loading`. Although the number of gpu workers increased from 1 to 2, I don't see any difference.
I also tried experimenting with `Dai.djl.pytorch.num_threads` but didn't see any change. 
Do you suspect I'm missing some sagemaker configuration to enable processing of requests concurrently?

Yes, I had tried with the `option.rolling_batch` earlier and it does give a much better throughput.

But I wanted to understand why doubling the models didn't give a better throughput.

Thanks!

**Comment by sneha5gsm** [comment]
Setting `env = {"NO_OMP_NUM_THREADS": "true"}` worked. The throughput more or less doubled as expected.
