### ISSUE TITLE
djl lmi images with vllm and hf quantizaton support

### ISSUE THREAD

**Issue by Nagarajj** [deepjavalibrary/djl-serving#1188]
## Description
Trying to use the below sample examples notebooks from dj-demo results in error as 0.24.0 image of djl-deepspeed isnt available? .

https://github.com/deepjavalibrary/djl-demo/blob/master/aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_llama_13b.ipynb

https://github.com/deepjavalibrary/djl-demo/blob/master/aws/sagemaker/large-model-inference/sample-llm/rollingbatch_deploy_llama2-13b-gptq.ipynb

@lanking520 and others whats the plan to release  0.24.0 images ? Or is there a way to get the latest images with the above support. Thanks 

### Expected Behavior
(what's the expected behavior?)
Ideal would be djl-deepspeed image which supports vllm and quantization schemes. 

### Error Message
image 0.24.0 isnt available

## How to Reproduce?
https://github.com/deepjavalibrary/djl-demo/blob/master/aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_llama_13b.ipynb

https://github.com/deepjavalibrary/djl-demo/blob/master/aws/sagemaker/large-model-inference/sample-llm/rollingbatch_deploy_llama2-13b-gptq.ipynb

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.
2.

## What have you tried to solve it?

1.
2.

**Comment by sindhuvahinis** [comment]
@Nagarajj 0.24 was released a while ago. Closing this issue as the release is done. Feel free to open a new one if you have any more questions.
