### ISSUE TITLE
Bug Report: TranslateException Error in DJL Serving - Missing token_type_ids in Model Forward Method

### ISSUE THREAD

**Issue by Quincynickyoung** [deepjavalibrary/djl-serving#1345]
## Description
I'm experiencing a TranslateException error when sending requests to a BERT model deployed using DJL Serving. The error indicates a missing token_type_ids argument in the model's forward method.

## Steps to Reproduce
1.Start the DJL Serving server with the BERT model loaded.
2.Send a POST request with text data, for example:
```
curl -X POST "http://localhost:8080/predictions/vector" -H "Content-Type: application/json" -d "[\"This is a test text\"]"
```
3.The server responds with a TranslateException error.
## Expected Behavior
I expected the server to process the text input and return the model's predictions without any errors.

## Actual Behavior
The request fails, resulting in the following error message:
```
{
  "code": 400,
  "type": "TranslateException",
  "message": "forward() is missing value for argument 'token_type_ids'. Declaration: forward(__torch__.transformers.models.bert.modeling_bert.BertModel self, Tensor input_ids, Tensor attention_mask, Tensor token_type_ids) -> Dict(str, Tensor)"
}
```
## Error Messages and Logs
The error message suggests that the model's forward method requires token_type_ids as an argument, which seems to be missing in the request.

## Environment Information
docker image: deepjavalibrary/djl-serving    
version: 0.23.0-pytorch-cu118
Model used: BERT (GanymedeNil_text2vec-large-chinese)

## Additional Context
my model directory contains:
```
config.json  eval_results.txt  model.py  README.md  serving.properties  special_tokens_map.json  tmparflkllc  tokenizer_config.json  tokenizer.json  traced_model.pt  vocab.txt
```
serving.properties:
```
pplication=nlp/text_vectorization
engine=PyTorch
translatorFactory=ai.djl.huggingface.translator.TextEmbeddingTranslatorFactory
option.modelName=traced_model
```
## Attempted Solutions
I have tried different request formats but couldn't resolve the issue.
Reviewed the DJL Serving documentation for any related configuration but found no relevant information.
Requesting Assistance
I am seeking guidance on how to resolve this issue. Specifically, I need to understand if the error is due to a configuration issue on the server-side or if it requires changes in the request format. Any insights or solutions would be highly appreciated.

**Comment by Quincynickyoung** [comment]
I got some confused about this doc:
```
https://github.com/deepjavalibrary/djl-demo/tree/master/djl-serving/workflows/python
```
It seems that I can load models based python with DJL Serving's workflow and it is unnecessary to use TranslatorFactory,right?

**Comment by frankfliu** [comment]
DJL support multiple engines, see: https://docs.djl.ai/docs/serving/serving/docs/modes.html

With Python engine, you can run any python code with `model.py`. However, run native `PyTorch` engine (C++) is much more efficient than Python.

You can add the following argument in `serving.properties` to fix your issue:

```
includeTokenTypes=true
```

**Comment by Quincynickyoung** [comment]
Adding this in ``serving.properties`` can not fix my issue
```
application=text_vectorization
engine=PyTorch
includeTokenTypes=true
translatorFactory=ai.djl.huggingface.translator.TextEmbeddingTranslatorFactory
option.modelName=vector
```
when I post the following request
```
curl -X POST "http://localhost:8080/predictions/vector" -H "Content-Type: text/plain" -d "this is a test text"
```
Still report error as follows
```
{
  "code": 400,
  "type": "TranslateException",
  "message": "forward() is missing value for argument \u0027token_type_ids\u0027. Declaration: forward(__torch__.transformers.models.bert.modeling_bert.BertModel self, Tensor input_ids, Tensor attention_mask, Tensor token_type_ids) -\u003e Dict(str, Tensor)"
}
```

In addition,I would be grateful if you could tell me where the doc about serving.properties's usage is.Maybe you could provide your email or other links so that I could seek your advice.
Thanks a lot!

**Comment by frankfliu** [comment]
You can join our slack channel, see: https://github.com/deepjavalibrary/djl#community

Are you using Huggingface mode? Can should share the model_id?

Is that possible you share your model?

**Comment by frankfliu** [comment]
We have this model in our model zoo, you can use the following command to run with DJLServing:

```
djl-serving -m djl://ai.djl.huggingface.pytorch/GanymedeNil/text2vec-large-chinese
```

And it works with the following curl:

```
curl -X POST "http://localhost:8080/invocations" -H "Content-Type: text/plain" -d "this is a test text"
```

You can download the model from your model zoo:
```
curl -O https://mlrepo.djl.ai/model/nlp/text_embedding/ai/djl/huggingface/pytorch/GanymedeNil/text2vec-large-chinese/0.0.1/text2vec-large-chinese.zip
```

You can also trace your model with the following command by yourself:

```
git clone https://github.com/deepjavalibrary/djl.git
cd djl/extensions/tokenizers/src/main/python
pip install -r requirements.txt
python model_zoo_importer.py -m GanymedeNil/text2vec-large-chinese
```
``
