### ISSUE TITLE
Using a Huggingface Token for vLLM Support 

### ISSUE THREAD

**Issue by ma3842** [deepjavalibrary/djl-serving#1471]
## Description

I am trying to implement vLLM for LLaMa 7b as a Sagemaker endpoint using the rolling_batch=vllm setting, however, I found that I could not deploy this model due to needing a Huggingface Token.

Is there anyway to provide this token without overriding the model.py file? I do not see a parameter here: https://docs.djl.ai/docs/serving/serving/docs/lmi/configurations_large_model_inference_containers.html

And if not, are there any resources for overriding the model.py to still take advantage of vllm for this task? From my understanding, the rolling batch overrides the general Huggingface inference and I'm not certain if it will do same for my custom model.py code.
All of the resources below use a default model.py with a modified, non-meta model 7b so it will be helpful if anyone had an example.

## References
https://github.com/vllm-project/vllm/issues/875
https://docs.djl.ai/docs/demos/aws/sagemaker/large-model-inference/sample-llm/vllm_deploy_llama_13b.html

**Comment by lanking520** [comment]
Yes, here: https://huggingface.co/docs/huggingface_hub/package_reference/environment_variables#hftoken Pass through environment variable

**Comment by ma3842** [comment]
Thank you @lanking520 . It is working now

**Comment by gsjoy8888** [comment]
Hi @ma3842, may I know how did you make it working? Thanks! Here's the env I used, it didn't work for me:

env={
        "HF_MODEL_ID": "mistralai/Mixtral-8x7B-Instruct-v0.1",
        "TENSOR_PARALLEL_DEGREE": "max",
        "OPTION_MAX_NUM_TOKENS": "8192",
        "OPTION_QUANTIZE": "awq",
        **"HF_TOKEN": "hf_xNBRqleBjkvQPnxxxxxxxxxxxxxxxxxxx"**
    }
