### ISSUE TITLE
Model Load Error when EngineProvider is MPI and entry point is djl_python.deepspeed for rolling batch type deepspeed

### ISSUE THREAD

**Issue by nskool** [deepjavalibrary/djl-serving#1509]
## Description
1. Setting the engine provider as MPI, and entry point is djl_python.deepspeed, errors out when rolling batch is 'deepspeed' with the following error `ValueError: Invalid rolling batch type: deepspeed`

### Expected Behavior
1. While the combination of EngineProvider: MPI and entry point: djl_python.deepspeed is not expected, we should either default to EngineProvider: DeepSpeed if entry point is djl_python.deepspeed 
(or)
2. Provide a more informative error message to request the user to set the engine provider as deepspeed

### Error Message
```
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:--- Logging error ---
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:Traceback (most recent call last):
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:  File "/tmp/.djl.ai/python/0.26.0/djl_python_engine.py", line 121, in run_server
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:    outputs = self.service.invoke_handler(function_name, inputs)
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:  File "/tmp/.djl.ai/python/0.26.0/djl_python/service_loader.py", line 29, in invoke_handler
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:    return getattr(self.module, function_name)(inputs)
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:  File "/tmp/.djl.ai/python/0.26.0/djl_python/huggingface.py", line 596, in handle
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:    _service.initialize(inputs.get_properties())
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:  File "/tmp/.djl.ai/python/0.26.0/djl_python/huggingface.py", line 146, in initialize
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:    _rolling_batch_cls = get_rolling_batch_class_from_str(
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:  File "/tmp/.djl.ai/python/0.26.0/djl_python/huggingface.py", line 102, in get_rolling_batch_class_from_str
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:    raise ValueError(f"Invalid rolling batch type: {rolling_batch_type}")
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:ValueError: Invalid rolling batch type: deepspeed
WARN  PyProcess W-248-llama-2-7b-hf-stderr: [1,0]<stderr>:
```

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)
2. To reproduce:
```
#! /bin/bash
SERVING_LOAD_MODELS=test::MPI=/opt/ml/model/llama-2-7b-hf/ #Note the `MPI` here
OPTION_MODEL_ID=/opt/ml/model/llama-2-7b-hf/
OPTION_TENSOR_PARALLEL_DEGREE=max
OPTION_MAX_ROLLING_BATCH_SIZE=8
OPTION_ROLLING_BATCH=deepspeed
OPTION_DTYPE=fp16
OPTION_ENTRY_POINT=djl_python.deepspeed


docker run -it --rm --network=host -v /home/ubuntu/llama-2-7b-hf/:/opt/ml/model/llama-2-7b-hf/ -v /home/ubuntu/.aws:/home/djl/.aws -v /home/ubuntu/sagemaker_infra/:/opt/ml/.sagemaker_infra/:ro -e TEST_TELEMETRY_COLLECTION=true -e SERVING_OPTS=-Dai.djl.logging.level=debug -u djl --runtime=nvidia --shm-size=12gb -e SERVING_LOAD_MODELS=$SERVING_LOAD_MODELS -e OPTION_MODEL_ID=$OPTION_MODEL_ID -e OPTION_ROLLING_BATCH=$OPTION_ROLLING_BATCH -e OPTION_TENSOR_PARALLEL_DEGREE=$OPTION_TENSOR_PARALLEL_DEGREE -e OPTION_MAX_ROLLING_BATCH_SIZE=$OPTION_MAX_ROLLING_BATCH_SIZE -e OPTION_DTYPE=$OPTION_DTYPE -e OPTION_ENTRY_POINT=$OPTION_ENTRY_POINT deepjavalibrary/djl-serving:0.26.0-deepspeed
```

## What have you tried to solve it?
Setting Engine Provider as DeepSpeed succeeds (as expected)
```
SERVING_LOAD_MODELS=test::DeepSpeed=/opt/ml/model/llama-2-7b-hf/ #Note the `DeepSpeed` here
```

**Comment by frankfliu** [comment]
I don't think we have `option.rolling_batch=deepspeed`
The valid values are:
- auto
- lmi-dist
- vllm
- trtllm
- scheduler

We need fix the document

**Comment by siddvenk** [comment]
We do have it as a value under the RollingBatchEnum https://github.com/deepjavalibrary/djl-serving/blob/master/engines/python/setup/djl_python/properties_manager/properties.py#L26.

The issue from above seems to be that when engine is specified as MPI, the option.entryPoint is not respected (djl_python.deepspeed was requested, but it's using djl_python.huggingface)

**Comment by nskool** [comment]
So it seems like `OPTION_ENTRY_POINT` cannot be used, instead `OPTION_ENTRYPOINT` must be used, due to the nature of the option itself - https://github.com/deepjavalibrary/djl-serving/blob/master/wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java#L732.

Additionally, for global setting  -`DJL_ENTRY_POINT` can be used: https://github.com/deepjavalibrary/djl-serving/blob/master/engines/python/src/main/java/ai/djl/python/engine/PyModel.java#L158.

If engine is MPI, setting `OPTION_ENTRYPOINT` or `DJL_ENTRY_POINT` to `djl_python.deepspeed` works as expected. 

The `ENTRY_POINT` (with the underscore) for global setting, and `ENTRYPOINT` (without underscore) for local setting is inconsistent. However, there's perhaps no bug here. Just a note for usability improvement.

Closing this issue.
