### ISSUE TITLE
DJL Serving ECR Image -  Sagemaker Realtime inference output token count

### ISSUE THREAD

**Issue by anshgandhi** [deepjavalibrary/djl-serving#1515]
## Description

When currently using DJL Serving ECR Image with Sagemaker Realtime inference - the response doesn't mention the completion/output token count. Is there a way to add that to the response or are there plans to support this feature in the future?

**Comment by frankfliu** [comment]
You can pass "detail" in request parameters, see: https://docs.djl.ai/docs/serving/serving/docs/lmi/lmi_input_output_schema.html#common-rolling-batch-input-parameters

And you will get "tokens" as a list, see: https://docs.djl.ai/docs/serving/serving/docs/lmi/lmi_input_output_schema.html#when-rolling-batch-is-enabled
