### ISSUE TITLE
Package shoudn't put into tags?

### ISSUE THREAD

**Issue by shenzhuangzhi1** [deepjavalibrary/djl-serving#164]
## Description

RT

**Comment by lanking520** [comment]
Currently we only do source code release as well as distribution to different OS. You can do snap install if you are on Linux, Brew install if you are on Mac OS. 

For all distribution, we also publish the packages under: ttps://publish.djl.ai/djl-serving/serving-0.17.0.zip

**Comment by shenzhuangzhi1** [comment]
thx
