### ISSUE TITLE
zephyr-7b-beta on sagemaker for inference

### ISSUE THREAD

**Issue by anshgandhi** [deepjavalibrary/djl-serving#1724]
## Description

https://huggingface.co/HuggingFaceH4/zephyr-7b-beta

using the zephyr-7b-beta model on SageMaker Image `djl-inference:0.24.0-deepspeed0.10.0-cu118` works and am able to deploy the model successfully. But, the newer image: `djl-inference:0.26.0-deepspeed0.12.6-cu121` is giving out an error: 
`The model's max seq len (32768) is larger than the maximum number of tokens that can be stored in KV cache (8848). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.`

Are there any recommended config changes that would solve for this?

### Error Message
`The model's max seq len (32768) is larger than the maximum number of tokens that can be stored in KV cache (8848). Try increasing `gpu_memory_utilization` or decreasing `max_model_len` when initializing the engine.`

## How to Reproduce?
using the following Engine & rolling_batch in serving.properties.
engine = Python
rolling_batch = vllm

**Comment by siddvenk** [comment]
There are two options:
1. Provide `option.max_model_len=<limit>` configuration. The limit can be 8848, which seems like the limit based on the current hardware you are using
2. Move to an instance with more GPUS/more GPU memory if you will require processing of longer sequence lengths

**Comment by anshgandhi** [comment]
yeah thought so.
The part I'm still trying to figure out is - it seemed to be deploying with a previous version of the image but not with the current (latest) one?
