### ISSUE TITLE
OOM when trying to serve Mixtral 8x7b on Inf2 with 32gb memory

### ISSUE THREAD

**Issue by yaronr** [deepjavalibrary/djl-serving#1847]
## Description
Running DJL serving on Mixtral 8x7b fails with out of memory (unable to allocate) while running on inf2.xlarge with 32GB of GPU memory.

### Expected Behavior
Since there are only 7b active parameters, and the tensor type is bf16, ~14GB of GPU memory should suffice. This device has 32GB of memory, so there should not be a memory issue.

### Error Message
WARN  PyProcess W-80-model-stderr: 2024-Apr-30 09:46:17.904255    80:80    ERROR  TDRV:dmem_alloc_internal                     Failed to alloc DEVICE memory: 469762048
WARN  PyProcess W-80-model-stderr: 2024-Apr-30 09:46:17.918106    80:80    ERROR  TDRV:dml_dump                                Wrote nrt memory alloc debug info to /tmp/nrt_mem_log_device_0_6630bde9.csv
WARN  PyProcess W-80-model-stderr: 2024-Apr-30 09:46:17.926062    80:80    ERROR  TDRV:log_dev_mem                             Failed to allocate 448.000MB (usage: tensors) on ND 0:NC 0, current utilization:
WARN  PyProcess W-80-model-stderr: 	* total: 15.785GB
WARN  PyProcess W-80-model-stderr: 	* tensors: 15.785GB
WARN  PyProcess W-80-model-stderr: 	* runtime: 1.062KB
WARN  PyProcess W-80-model-stderr: 	* dma rings: 32.000KB
WARN  PyProcess W-80-model-stderr: 

## How to Reproduce?
docker run -e HUGGING_FACE_HUB_TOKEN=xx -e OPTION_ENTRYPOINT=djl_python.transformers_neuronx -e OPTION_TRUST_REMOTE_CODE=true -e SERVING_LOAD_MODELS=test::Python=/opt/ml/model -e OPTION_TENSOR_PARALLEL_DEGREE=2 -e OPTION_MODEL_ID=mistralai/Mixtral-8x7B-Instruct-v0.1  --device /dev/neuron0 -d  --name djl-mixtral -p 8080:8080 763104351884.dkr.ecr.$AWS_REGION.amazonaws.com/djl-inference:0.27.0-neuronx-sdk2.18.1

**Comment by tosterberg** [comment]
I think that you might be using the wrong model - mistralai/Mixtral-8x7B-Instruct-v0.1 has eight 7b models in a mixture of experts arrangement, for 112GB of model weights. If you are wanting to use the original mistral 7b, the 0.2 version is this mistralai/Mistral-7B-Instruct-v0.2 which is about 14GB which should fit on the smaller instance.

**Comment by yaronr** [comment]
You are absolutely right, sorry - I will close the issue.

**Comment by yaronr** [comment]
Closing
