### ISSUE TITLE
Add "disable-sliding-window" VLLM/LMI-dist engine argument to enable running Phi-3-Vision with Flash Attn

### ISSUE THREAD

**Issue by hommayushi3** [deepjavalibrary/djl-serving#2337]
## Description

When I try to run Phi-3-vision with flash attention using DJL serving on sagemaker (0.29.0 image), I get a warning saying "Cannot use FlashAttention-2 backend due to sliding window." To fix this, VLLM supports [an Engine parameter called disable-sliding-window](https://docs.vllm.ai/en/latest/models/engine_args.html#named-arguments) that successfully allows Phi-3-vision to run with FlashAttention-2 instead of Xformers. However, DJL serving does not support this parameter. Please add this as an option that can be set via serving.properties AND the environment variable options.

**Comment by tosterberg** [comment]
Reviewed PR - one small change to the documentation then it LGTM, thank you for your contribution!
