### ISSUE TITLE
Support for newer Vision LMs through vllm 0.6.1

### ISSUE THREAD

**Issue by rdzotz** [deepjavalibrary/djl-serving#2387]
## Description

Upgrade vllm backend to 0.6.1 thereby allowing newer models such as Phi 3.5 v instruct or Pixtral

Who will benefit from this enhancement?
Considerable improvements in multi-model inference and overall performance of these models

## References
https://huggingface.co/mistralai/Pixtral-12B-2409
https://huggingface.co/microsoft/Phi-3.5-vision-instruct

**Comment by siddvenk** [comment]
we have upgraded to 0.6.2 vllm and supported the additional vlms. You can find an example for pixtral here https://github.com/deepjavalibrary/djl-demo/blob/master/aws/sagemaker/large-model-inference/sample-llm/multi-modal-pixtral-12b.ipynb
