### ISSUE TITLE
docker pull   is very slowly

### ISSUE THREAD

**Issue by oswardlx** [deepjavalibrary/djl-serving#256]
## Description

(A clear and concise description of what the feature is.)

Will this change the current api? How?

Who will benefit from this enhancement?

## References
- list reference and related literature
- list known implementations

**Comment by frankfliu** [comment]
djl-serving docker image is only 300M, see: https://hub.docker.com/r/deepjavalibrary/djl-serving/tags

The slow might be either on dockerhub side or your network. There is nothing we can do.

**Comment by lanking520** [comment]
Of you are using dockerhub in China, try this:

https://github.com/Azure/container-service-for-azure-china/blob/master/aks/README.md#22-container-registry-prox

```
dockerhub.azk8s.cn/deepjavalibrary/djl-serving:latest
```

**Comment by oswardlx** [comment]
thanks
