### ISSUE TITLE
GitHub Action Patching [2023/05/31]

### ISSUE THREAD

**Issue by lanking520** [deepjavalibrary/djl-serving#305]
## Description

update set-output for DJL, DJL Demo and DJLServing

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by frankfliu** [comment]
I don't think we are using these features.

**Comment by lanking520** [comment]
we are using, in the Action create instance stage

**Comment by frankfliu** [comment]
Fixed.
