### ISSUE TITLE
About release 0.20.0

### ISSUE THREAD

**Issue by chenrui333** [deepjavalibrary/djl-serving#334]
It looks like there is [0.20.0 release](https://github.com/deepjavalibrary/djl/releases/tag/v0.20.0), but there is no downloadable artifact for `https://publish.djl.ai/djl-serving/serving-0.20.0.tar`, raising this issue to confirm if there is anything missing in the release process. Thanks!

**Comment by frankfliu** [comment]
The latest release is 0.19.0. DJL 0.20.0 has not released yet.

You can find nightly deb file: https://publish.djl.ai/djl-serving/djl-serving_0.20.0~SNAPSHOT-1_all.deb

**Comment by chenrui333** [comment]
@frankfliu thanks for the reply, where would be the place to check the latest release announcement?

**Comment by frankfliu** [comment]
The release note will be published in DJL github: https://github.com/deepjavalibrary/djl/releases

**Comment by chenrui333** [comment]
Sounds good, thanks!!

**Comment by chenrui333** [comment]
@frankfliu I think now we have a djl 0.20.0, but the release is still missing on the dji-serving side. Did I miss anything?

**Comment by lanking520** [comment]
@chenrui333 there has been a delay on DJLServing release due to some essential bug fixing. We will cut the release by 12.9
