### ISSUE TITLE
Is there any example about this "map" operation？

### ISSUE THREAD

**Issue by oswardlx** [deepjavalibrary/djl-serving#415]
As a final example, here is one that features a more complicated interaction. The human detection model will find all of the humans in an image. Then, the "splitHumans" function will turn all of them into separate images that can be treated as a list. The "map" will apply the "poseEstimation" model to each of the detected humans in the list.

workflow:
  humans: ["splitHumans", ["humanDetection", "in"]]
  out: ["map", "poseEstimation", "humans"]

**Comment by zachgk** [comment]
For clarification, the code here is not a real example, more of a pseudo-code to describe how the workflow system works.   The available workflow functions can be found within the [package `ai.djl.serving.workflow.function`'s javadoc](https://javadoc.io/doc/ai.djl.serving/serving/latest/ai/djl/serving/workflow/function/package-summary.html).

If you are interested, there is a plan to build a real example based on this and the [Pose Estimation example](https://github.com/deepjavalibrary/djl/blob/master/examples/docs/pose_estimation.md).
