### ISSUE TITLE
hope this project can have a login page

### ISSUE THREAD

**Issue by oswardlx** [deepjavalibrary/djl-serving#418]
I'd like to use the UI control panel plugin，but there is no security verification so that I dare not open the UI page in the production environment.

Can you add a simple login page？even if only one admin's account. I think it will be very helpful to the development of the project

**Comment by oswardlx** [comment]
At present, in order to use in the production environment, I have deleted the add, delete, and modify related interfaces, and only opened the query interface. I also want to use the full function. The ui plugin is really convenient, but it needs a login function

**Comment by oswardlx** [comment]
At present, in order to use in the production environment, I have deleted the add, delete, and modify related interfaces, and only opened the query interface. I also want to use the full function. The ui plugin is really convenient, but it needs a login function

**Comment by frankfliu** [comment]
DJLServing have two connector:
1. inference - `inference_address=http://127.0.0.1:8080`, listening on localhost only, you need to make it public for production use
2. manage - `management_address=http://127.0.0.1:8080`, you can open this port to localhost only or only expose to internal network, and use ip filter to allow access only from certain IP address.

**Comment by oswardlx** [comment]
@frankfliu 
it works ,thanks, but can't achieve the effect of out of the box use。

you said we can consider DJLServer as tomcat
https://github.com/deepjavalibrary/djl-serving/issues/293#issuecomment-1280330077

But tomcat management terminal has login page, so do you want to consider adding a login page.it really helpful !
