### ISSUE TITLE
djl-serving language support

### ISSUE THREAD

**Issue by oswardlx** [deepjavalibrary/djl-serving#422]
When I used djl-serving 0.19.0, I found that the predicted result of the model was garbled in Chinese.

Later, I found that the image of ubuntu does not support Chinese. Later, I added the installation of language-pack-zh-hans in install_djl_serving.sh, and added 

`RUN localedef -c -f UTF-8 -i zh_CN zh_CN.utf8`
`ENV LC_ALL zh_CN.UTF-8`

to Dockerfile to make a new image.Finally it support prediction results in Chinese.

Is my handling correct? Or the prediction results originally support Chinese, but there is a problem with my model.

Or do you intend to support the prediction results in Chinese?

**Comment by frankfliu** [comment]
@oswardlx Can you provide a sample model to reproduce your issue?

Not sure why the model depends on default locale, it's OK to install zh locale in the docker, but need to understand why it depends on default locale.
