### ISSUE TITLE
Support Torch-TensorRT / quantized inference for pytorch models?

### ISSUE THREAD

**Issue by jxtps** [deepjavalibrary/djl-serving#433]
(Apologies if this is already supported, the docs are unclear/confusing)

DJL-serving claims support for TensorRT model on https://github.com/deepjavalibrary/djl-serving

DJL FAQ doesn't mention support for TensorRT: https://djl.ai/docs/faq.html - ??

I have a pytorch model that I'd like to run inference on. For memory & performance reasons I'd like to quantize it to at least fp16, ideally uint8. To not run into quantization issues (which I do if I just change the format of the weights to fp16 in my pytorch -> torchscript model) I need to apply Post-Training-Quantization with suitable calibration. 

The only path I've found to actually do that with pytorch is via TensorRT: 

1. https://developer.nvidia.com/tensorrt 
2. https://developer.nvidia.com/blog/accelerating-inference-up-to-6x-faster-in-pytorch-with-torch-tensorrt/ 
3. https://pytorch.org/TensorRT/tutorials/ptq.html#ptq

However, that creates something that is neither a torchscript nor a TensorRT model, it's instead some Torch-TensorRT hybrid. Ok. Now, to deploy that monstrosity their docs ( https://pytorch.org/TensorRT/tutorials/runtime.html#runtime ) claim that all you have to do is link in `libtorchtrt_runtime.so` that's included in their C++ distribution. Great. 

Is it possible to do that and use this workflow with DJL serving? Has anyone done it? 

Is there another (better) path to get quantized inference in DJL?

Thanks!

**Comment by frankfliu** [comment]
@jxtps 
The FAQ is outdated, I created a [PR](https://github.com/deepjavalibrary/djl/pull/2328) to update it.

We currently doesn't support Torch-TRT. Most our customers convert PyTorch model to ONNX, use our ONNXRuntime engine to serve the model.

There are two ways to use TensorRT with ONNX model:
1. Use ONNXRuntime engine and specify "ortDevice" as "TensorRT":
```
            Criteria<NDList, NDList> criteria =
                    Criteria.builder()
                            .setTypes(NDList.class, NDList.class)
                            .optEngine("OnnxRuntime") // use OnnxRuntime engine
                            .optOption("ortDevice", "TensorRT")
                            .build();
```
2. Use TensorRT engine directly, see: [example](https://github.com/deepjavalibrary/djl/blob/master/engines/tensorrt/src/test/java/ai/djl/tensorrt/integration/TrtTest.java#L58-L64). With TensorRT engine, you can pass options when you loading the model to runtime quantize your model into int8 or fp16.

**Comment by jxtps** [comment]
Ok, thanks!
