### ISSUE TITLE
Please add unit suffixes to relevant variables/methods

### ISSUE THREAD

**Issue by jxtps** [deepjavalibrary/djl-serving#434]
In e.g. 
```java
    public ModelInfo(
            String id,
            String modelUrl,
            String version,
            String engineName,
            Class<I> inputClass,
            Class<O> outputClass,
            int queueSize,
            int maxIdleTime,
            int maxBatchDelay,
            int batchSize) {
```
there's no indication what the unit of time or delay is for `maxIdleTime` or `maxBatchDelay`. This makes it frustrating to use the library as I have to click through a bunch of source code to see actual usage to infer what's intended. 

It makes the library a lot easier to use if cases like that are named e.g. `maxIdleTimeSecs` and `maxBatchDelayMillis`. 

This appears pervasive - e.g. `Job.getBegin` (which should probably be removed as System.nanoTime() isn't absolute?) and `Job.getWaitingTime` (-> `Job.getWaitingTimeMicrosecs`)

`Time` can usually be omitted if it's obvious, e.g. `Job.getWaitingMicrosecs`, `maxIdleSecs`.

**Comment by frankfliu** [comment]
@jxtps 
You brought up a very good point, will work on it.
