### ISSUE TITLE
First ModelInfo constructor leaves queueSize etc uninitialized

### ISSUE THREAD

**Issue by jxtps** [deepjavalibrary/djl-serving#435]
https://github.com/deepjavalibrary/djl-serving/blob/master/wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java#L75-L80 currently reads: 

```java
    public ModelInfo(String modelUrl, Class<I> inputClass, Class<O> outputClass) {
        this.id = modelUrl;
        this.modelUrl = modelUrl;
        this.inputClass = inputClass;
        this.outputClass = outputClass;
    }
```
This is missing the default initialization of `queueSize` et al present in the `Criteria`-constructor just below ( https://github.com/deepjavalibrary/djl-serving/blob/master/wlm/src/main/java/ai/djl/serving/wlm/ModelInfo.java#L88-L99 ):
 ```java
        WlmConfigManager config = WlmConfigManager.getInstance();
        queueSize = config.getJobQueueSize();
        maxIdleTime = config.getMaxIdleTime();
        batchSize = config.getBatchSize();
        maxBatchDelay = config.getMaxBatchDelay();
```

This makes the first constructor not very useful?

**Comment by frankfliu** [comment]
This is not a bug.

batchSize, queueSize, maxIdleTime and maxBatchDelay comes from 3 source in the following order:
1. global default value read from `conf.properties` file (or environment variable). the default values is hold in WlmConfigManager
2. per model settings in each model's `serving.properties`, the value will be read only at model loading time, this override default value in WlmConfigManager.
3. explicitly set in model registration API, this override model's settings
