### ISSUE TITLE
Unable to deploy GPT-Neox using Large Model inference container

### ISSUE THREAD

**Issue by pinak-p** [deepjavalibrary/djl-serving#440]
## Description
(A clear and concise description of what the bug is.)
Deploying GPT-Neox (https://huggingface.co/EleutherAI/gpt-neox-20b) on SageMaker is unsuccessful.

### Expected Behavior
(what's the expected behavior?)
Successfully deploy the model to a SageMaker endpoint using the latest version of the Large Model Inference container. (https://github.com/aws/deep-learning-containers/blob/master/available_images.md)

### Error Message
(Paste the complete error message, including stack trace.)
`[INFO ] PyProcess - [1,2]<stdout>:  File "/root/.djl.ai/python/0.20.0/djl_python/deepspeed.py", line 207, in _validate_model_type_and_task`
`[INFO ] PyProcess - [1,2]<stdout>:ValueError: model_type: gpt_neox is not currently supported by DeepSpeed`

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

Using the following configuration in serving.properties

```
engine = DeepSpeed
option.entryPoint=djl_python.deepspeed
option.tensor_parallel_degree=8
option.model_id=EleutherAI/gpt-neox-20b
```

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.  Create a SageMaker model and model configuration and then create an endpoint.

## What have you tried to solve it?
`gpt-neox` is listed in the SUPPORTED_MODEL_TYPES  - https://github.com/deepjavalibrary/djl-serving/blob/master/engines/python/setup/djl_python/deepspeed.py#L39. 

Examining the `model_type` using the following code - 
```
from transformers import AutoConfig
model_config = AutoConfig.from_pretrained("EleutherAI/gpt-neox-20b")
model_config.model_type
```

shows that it is probably `gpt_neox`.

**Comment by frankfliu** [comment]
Tested with latest deepspeed-nightly docker image, gpt-neox-20b can be loaded successfully in less than 3 mins.
