### ISSUE TITLE
Is there any way to build a gpu docker image based on Onnx?

### ISSUE THREAD

**Issue by oswardlx** [deepjavalibrary/djl-serving#495]
Can we create a new gpu Dockerfile based on Onnx?

**Comment by frankfliu** [comment]
Our current `deepjavalibrary/djl-serving:0.20.0-pytorch-cu117` docker should work for ONNX.
ONNX GPU engine will be downloaded on the fly when you deploy a onnx model

**Comment by frankfliu** [comment]
If you want to add ONNX engine in the docker, you run the following command in your docker file:

```
djl-serving -i ai.djl.onnxruntime:onnxruntime-engine:0.21.0
djl-serving -i com.microsoft.onnxruntime:onnxruntime_gpu:1.14.0
```

See example: in our docker script: https://github.com/deepjavalibrary/djl-serving/blob/master/serving/docker/scripts/install_djl_serving.sh#LL26C5-L26C76
