### ISSUE TITLE
Was 0.21.0 source tarball updated?

### ISSUE THREAD

**Issue by ZhongRuoyu** [deepjavalibrary/djl-serving#562]
## Description
(A clear and concise description of what the bug is.)

While packaging OpenJDK for Homebrew, it was noticed that DJL Serving's tarball, downloaded from https://publish.djl.ai/djl-serving/serving-0.21.0.tar, reported a different checksum. It used to be `8fa8afd1a4181fc55e6ad2cb31cea8ec07fc4ad5df135e62bd07106ce3fc6c80` at 2023-02-26 03:36 UTC, but now it is `523c742f80fb277bfc7f8c3f706ede4b28fbc5d95851d526f63d7e6f02c6c423`. May I confirm if the tarball is re-uploaded? Thanks!

### Expected Behavior

Tarball checksum should match the one in our [formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/djl-serving.rb) (package description).

### Error Message
(Paste the complete error message, including stack trace.)

See CI failure [here](https://github.com/Homebrew/homebrew-core/actions/runs/4488442125/jobs/7893146179?pr=126319#step:11:2602):

```
  ==> Downloading https://publish.djl.ai/djl-serving/serving-0.21.0.tar
  Downloaded to: /Users/brew/Library/Caches/Homebrew/downloads/acdf5ceb0cf03acc49888f36839af1c9e017be2fce0c48dc17d9641f01945263--serving-0.21.0.tar
  SHA256: 523c742f80fb277bfc7f8c3f706ede4b28fbc5d95851d526f63d7e6f02c6c423
  Warning: Formula reports different sha256: 8fa8afd1a4181fc55e6ad2cb31cea8ec07fc4ad5df135e62bd07106ce3fc6c80
```

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

```console
$ curl -L https://publish.djl.ai/djl-serving/serving-0.21.0.tar | shasum -a256 -
523c742f80fb277bfc7f8c3f706ede4b28fbc5d95851d526f63d7e6f02c6c423  -
```

### Steps to reproduce
(Paste the commands you ran that produced the error.)

See above.

## What have you tried to solve it?

N/A.

**Comment by frankfliu** [comment]
Thanks for reporting this issue. I guess this was caused by delayed update of cloudfront caching. I just confirmed that your PR is the latest jar ball.
