### ISSUE TITLE
Bug in streaming

### ISSUE THREAD

**Issue by sunlijia-amazon-ai** [deepjavalibrary/djl-serving#670]
## Description
At line 183 of streaming_utils.py: https://github.com/deepjavalibrary/djl-serving/blob/master/engines/python/setup/djl_python/streaming_utils.py#L183

### Error Message
Traceback (most recent call last):
  File "/home/ubuntu/models/linguist/djl-model/steaming_test.py", line 68, in <module>
    next_token_id = decoding_method(
  File "/home/ubuntu/models/linguist/djl-model/streaming_utils.py", line 189, in _sampling_decoding
    logits[-1:, :] = processors(input_ids, logits[-1:, :])
RuntimeError: Output 0 of SliceBackward0 is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

## What have you tried to solve it?
replace line 183 with following:
        _logits = logits.detach().clone()
        _logits[-1:, :] = processors(input_ids, logits[-1:, :])
        logits = _logits

**Comment by rohithkrn** [comment]
@sunlijia-amazon-ai could you provide a reproducible? We have not seen this error on our side.

**Comment by sindhuvahinis** [comment]
Streaming for Seq2Seq model is available now. Shall we close this issue? @sunlijia-amazon-ai
