### ISSUE TITLE
LMI container not compatible with Multi-container endpoint of SageMaker

### ISSUE THREAD

**Issue by dhawalkp** [deepjavalibrary/djl-serving#708]
## Description
The DJL containers should be added with Docker label to enable it in multi-container endpoint in SageMaker.
Currently, its not enabled and users gets below error -

An error occurred (ValidationException) when calling the CreateModel operation: Your Ecr Image 763104351884.dkr.ecr.us-east-1.amazonaws.com/djl-inference:0.21.0-fastertransformer5.3.0-cu117 does not contain required com.amazonaws.sagemaker.capabilities.accept-bind-to-port=true Docker label(s).

(A clear and concise description of what the feature is.)

Will this change the current api? How?
Change the dockerfile and add the label

Who will benefit from this enhancement?
All SageMaker customers

## References
- list reference and related literature
- list known implementations

**Comment by lanking520** [comment]
@dhawalkp Yo: https://github.com/deepjavalibrary/djl-serving/pull/706

**Comment by dhawalkp** [comment]
I see this pull request is addressing the enhancement. https://github.com/deepjavalibrary/djl-serving/pull/706
