### ISSUE TITLE
using paddlepaddle engine and ppocr-v3 model an error occurred

### ISSUE THREAD

**Issue by faquir-sun** [deepjavalibrary/djl-serving#864]
## Description
(A clear and concise description of what the bug is.)

### Expected Behavior
(what's the expected behavior?)

### Error Message
(Paste the complete error message, including stack trace.)
INFO  ModelManager Loading model on PaddlePaddle:[cpu]
INFO  WorkerPool loading model det_infer:1 on cpu() ...
INFO  ModelInfo Available CPU memory: 2097151 MB, required: 0 MB, reserved: 500 MB
INFO  ModelInfo Loading model det_infer on cpu()
W0624 19:04:12.082520 238272512 analysis_predictor.cc:1736] Deprecated. Please use CreatePredictor instead.
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_graph_clean_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [layer_norm_fuse_pass]
---    Fused 0 subgraphs into layer_norm op.
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]
--- Running IR pass [mul_lstm_fuse_pass]
--- Running IR pass [fc_gru_fuse_pass]
---    fused 0 pairs of fc gru patterns
--- Running IR pass [mul_gru_fuse_pass]
--- Running IR pass [seq_concat_fc_fuse_pass]
--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]
--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]
--- Running IR pass [matmul_v2_scale_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]
--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]
--- Running IR pass [matmul_scale_fuse_pass]
--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]
--- Running IR pass [fc_fuse_pass]
--- Running IR pass [repeated_fc_relu_fuse_pass]
--- Running IR pass [squared_mat_sub_fuse_pass]
--- Running IR pass [conv_bn_fuse_pass]
I0624 19:04:12.248106 238272512 fuse_pass_base.cc:57] ---  detected 33 subgraphs
--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]
--- Running IR pass [conv_transpose_bn_fuse_pass]
--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]
I0624 19:04:12.287765 238272512 fuse_pass_base.cc:57] ---  detected 1 subgraphs
--- Running IR pass [is_test_pass]
--- Running IR pass [runtime_context_cache_pass]
--- Running analysis [ir_params_sync_among_devices_pass]
--- Running analysis [adjust_cudnn_workspace_size_pass]
--- Running analysis [inference_op_replace_pass]
--- Running analysis [ir_graph_to_program_pass]
I0624 19:04:12.387943 238272512 analysis_predictor.cc:1035] ======= optimize end =======
I0624 19:04:12.388329 238272512 naive_executor.cc:102] ---  skip [feed], feed -> x
I0624 19:04:12.393230 238272512 naive_executor.cc:102] ---  skip [sigmoid_0.tmp_0], fetch -> fetch
INFO  WorkerPool scale up 1 workers (1 - 16)
I0624 19:04:12.394218 238272512 naive_executor.cc:102] ---  skip [feed], feed -> x
I0624 19:04:12.400275 238272512 naive_executor.cc:102] ---  skip [sigmoid_0.tmp_0], fetch -> fetch
WARN  WorkerThread Failed to predict
ai.djl.translate.TranslateException: Input is not a NDList data type
	at ai.djl.translate.NoopServingTranslatorFactory$NoopServingTranslator.processInput(NoopServingTranslatorFactory.java:70) ~[api-0.23.0-SNAPSHOT.jar:?]
	at ai.djl.translate.NoopServingTranslatorFactory$NoopServingTranslator.processInput(NoopServingTranslatorFactory.java:48) ~[api-0.23.0-SNAPSHOT.jar:?]
	at ai.djl.inference.Predictor.batchPredict(Predictor.java:168) ~[api-0.23.0-SNAPSHOT.jar:?]
	at ai.djl.serving.wlm.WorkerThread.run(WorkerThread.java:97) [wlm-0.23.0-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.IllegalArgumentException: Invalid NDList size: -2555936
	at ai.djl.ndarray.NDList.decode(NDList.java:105) ~[api-0.23.0-SNAPSHOT.jar:?]
	at ai.djl.modality.Input.getAsNDList(Input.java:351) ~[api-0.23.0-SNAPSHOT.jar:?]
	at ai.djl.modality.Input.getDataAsNDList(Input.java:221) ~[api-0.23.0-SNAPSHOT.jar:?]
	at ai.djl.translate.NoopServingTranslatorFactory$NoopServingTranslator.processInput(NoopServingTranslatorFactory.java:68) ~[api-0.23.0-SNAPSHOT.jar:?]
	... 8 more

## How to Reproduce?
(If you developed your own code, please provide a short script that reproduces the error. For existing examples, please provide link.)

### Steps to reproduce
(Paste the commands you ran that produced the error.)

1.docker pull deepjavalibrary/djl-serving:cpu-full-nightly
2.docker run -itd --name djl-serving -p 8080:8080 deepjavalibrary/djl-serving:cpu-full-nightly
3.access web ui upload model file and run test

Using 0.22.1 is also the same error

## What have you tried to solve it?

1.
2.

**Comment by frankfliu** [comment]
You need pass a serialized `NDList` or `.npz` data as input to run the inferenec.

You can use java client to make request to model server, see: https://github.com/deepjavalibrary/djl-demo/tree/master/djl-serving/java-client 

You can also try use python client, see: https://github.com/deepjavalibrary/djl-demo/tree/master/djl-serving/python-client

**Comment by faquir-sun** [comment]
I just tried DJL, how to convert image to NDList or .npz format? I use javaclient and got the same error
<img width="590" alt="image" src="https://github.com/deepjavalibrary/djl-serving/assets/16932704/e54d56ec-ebd2-4dc5-986b-9c22934a9120">

**Comment by frankfliu** [comment]
Please take a look this example:

https://github.com/deepjavalibrary/djl-demo/blob/master/djl-serving/java-client/src/main/java/ai/djl/examples/serving/javaclient/DJLServingClientExample4.java

**Comment by faquir-sun** [comment]
Thanks bro, I have another question. PaddleOCR has three models, how should I concatenate them in the configuration
