### ISSUE TITLE
Are there any plans to expose the skip_special_tokens parameter in the future, driven by serving configuration?

### ISSUE THREAD

**Issue by extraleo** [deepjavalibrary/djl-serving#900]
![image](https://github.com/deepjavalibrary/djl-serving/assets/22816086/dedf4282-358c-4a43-91b3-0d24870eb3ff)
 https://github.com/deepjavalibrary/djl-serving/blob/d3ecca3ed0cccead885f6b68c2c5b977198a2446/engines/python/setup/djl_python/deepspeed.py#L367C32-L367C51

For developers working on relevant applications, the truncation of certain endoftext tokens is helpful for the extraction of answers.

**Comment by frankfliu** [comment]
@extraleo 

If you are interested this feature, would you mind create a PR to add skip_special_tokens support?

**Comment by frankfliu** [comment]
deepspeed handler is deprecated. Closing this issue.
