### ISSUE TITLE
Listener timed out in: 30.0 s

### ISSUE THREAD

**Issue by yuxin7** [deepjavalibrary/djl-serving#950]
![image](https://github.com/deepjavalibrary/djl-serving/assets/35183358/ff8727ec-a8b4-42bf-814e-9670271c2d36)

**Comment by frankfliu** [comment]
Can you reproduce this issue consistently?
What's the CPU utilization when you see this error?
Are you using our docker container?

It looks like your python process startup takes more than 30 seconds, did you installed a lot of PIP packages?

**Comment by yuxin7** [comment]
> 你能始终如一地重现这个问题吗？看到此错误时的 CPU 利用率是多少？您是否正在使用我们的码头工人容器？
> 
> 看起来您的python进程启动需要30多秒，您是否安装了很多PIP

> 你能始终如一地重现这个问题吗？看到此错误时的 CPU 利用率是多少？您是否正在使用我们的码头工人容器？
> 
> 看起来您的python进程启动需要30多秒，您是否安装了很多PIP软件包？

只是在加载新的模型出现了这个问题。应该不是CPU利用率的问题。

**Comment by yuxin7** [comment]
> > 你能始终如一地重现这个问题吗？看到此错误时的 CPU 利用率是多少？您是否正在使用我们的码头工人容器？
> > 看起来您的python进程启动需要30多秒，您是否安装了很多PIP
> 
> > 你能始终如一地重现这个问题吗？看到此错误时的 CPU 利用率是多少？您是否正在使用我们的码头工人容器？
> > 看起来您的python进程启动需要30多秒，您是否安装了很多PIP软件包？
> 
> 只是在加载新的模型出现了这个问题。应该不是CPU利用率的问题。

使用的python环境没有很多的pip包

**Comment by frankfliu** [comment]
Closing old issue. Feel free to reopen it if you can reproduce it in latest version.
