### ISSUE TITLE
Unable to to download from s3

### ISSUE THREAD

**Issue by monuminu** [deepjavalibrary/djl-serving#962]
## Description
As model_id can be either huggingface model or s3 location. But when I put s3 it fails . 

### Expected Behavior
It should be able to run

### Error Message
ERROR "sync s3://sagemaker-us-east-1-*/huggingface-model/output/model.tar.gz/* /tmp/.djl.ai/download/tmp

**Comment by frankfliu** [comment]
`option.model_id` must point to a s3 prefix. It cannot be a file. This feature allows user package model weight externally to the model package (.zip or .tar.gz) file to improve the s3 download speed. The files in this s3 location must be directly consumable by the model code. Model server will not trying to uncompress the archive file.
